### PR TITLE
Update TemplateTimings.py

### PR DESCRIPTION
**Pull request by iho**
Hi! 

I am trying work under django 1.9 

```
from django.template import base as template_base

def _tag_compiler(func):

    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        if 'node_class' in kwargs:
            wrap_generic_node(kwargs['node_class'], kwargs['name'])
            FOUND_GENERIC_NODES.add((kwargs['node_class'], kwargs['name']))
        return func(*args, **kwargs)

    return wrapper

template_base.generic_tag_compiler = _tag_compiler(
    template_base.generic_tag_compiler)
```
Do u even use this code?

### CODE REVIEW

**Comment by bashu** [comment]
+1

**Comment by karyon** [comment]
@orf ping. if i understand correctly, they asked whether that code is used because django.template.base.generic_tag_compiler got removed/refactored and that line doesn't work anymore.

**Comment by karyon** [comment]
@orf sorry if i was unclear, i think this still won't work in django 1.9 because of the generic_tag_compiler stuff that got refactored.

**Comment by orf** [comment]
Sorry, I've rather dropped the ball on this project. I've merged this request and pushed a new release to PyPi, but I'm unsure if it actually works still. I think I'm going to do a full re-write at some point to attempt to support both Django and Jinja2 templates, but I currently don't use any templates for my work so I'm not sure where I will get the time.

**Pull request merged**
